<template>
    <div class='about'>
        <h1 style="font-size:36px;">ABOUT ME</h1>
        <p style="font-size:24px;">Saranyapong Tarama</p>
        <p style="font-size:24px;">560610175</p>
    </div>
</template>

<style>
#app {
  text-align: center;
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #2c3e50;
}
</style>